apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: tutoria
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: ARNIAK123
  MYSQL_DATABASE: tutorias
  MYSQL_USER: user_tutoria
  MYSQL_PASSWORD: pass_tutoria
